//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KINOwpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmsDatesSeances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilmsDatesSeances()
        {
            this.ReservationCodes = new HashSet<ReservationCodes>();
            this.SoldPlaces = new HashSet<SoldPlaces>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FilmsDatesId { get; set; }
        public Nullable<int> SeanceId { get; set; }
    
        public virtual FilmsDates FilmsDates { get; set; }
        public virtual Seances Seances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationCodes> ReservationCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoldPlaces> SoldPlaces { get; set; }
    }
}
