//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KINOwpf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KINOdbEntities : DbContext
    {
        public KINOdbEntities()
            : base("name=KINOdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Dates> Dates { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<FilmsDates> FilmsDates { get; set; }
        public virtual DbSet<FilmsDatesSeances> FilmsDatesSeances { get; set; }
        public virtual DbSet<FilmsGenres> FilmsGenres { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Prices> Prices { get; set; }
        public virtual DbSet<ReservationCodes> ReservationCodes { get; set; }
        public virtual DbSet<ReservationPlaces> ReservationPlaces { get; set; }
        public virtual DbSet<Seances> Seances { get; set; }
        public virtual DbSet<SoldPlaces> SoldPlaces { get; set; }
        public virtual DbSet<Subscriptions> Subscriptions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
