//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KINOwpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationPlaces
    {
        public int Id { get; set; }
        public int Range { get; set; }
        public int Place { get; set; }
        public Nullable<int> CodeId { get; set; }
        public Nullable<int> ReservationCode_Id { get; set; }
        public int Price { get; set; }
        public bool Student { get; set; }
        public bool Retiree { get; set; }
    
        public virtual ReservationCodes ReservationCodes { get; set; }
    }
}
