//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KINOwpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldPlaces
    {
        public int Id { get; set; }
        public int Range { get; set; }
        public int Place { get; set; }
        public Nullable<int> FilmDateSeanceId { get; set; }
    
        public virtual FilmsDatesSeances FilmsDatesSeances { get; set; }
    }
}
